import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Button, Stack, Typography } from '@mui/material'



const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack padding={2} spacing={2}>
        <div className="flex flex-col items-center justify-center rounded-sm bg-cover bg-[url('../public/blue-water.jpg')] md:sm:bg-[url('../public/starboard-tack.jpg')] h-screen">
          <Typography
            variant='h1'            
          >
            Yachteee
          </Typography>
          <Button
            color='primary'
            variant='contained'
            sx={{margin: 2}}
          >
          Enter App
        </Button>       
        </div>
      </Stack>
    </>
  )
}
