import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Button, Stack, Typography, useMediaQuery } from '@mui/material'
import { signIn, signOut, useSession } from 'next-auth/react';
import { useRouter } from 'next/router';
import { useQuery } from '@apollo/client';
import { GET_YC_MEMBER } from '@/lib/gqlQueries/yachtygql';
import { useDispatch } from 'react-redux';
import { addMember } from '@/slices/actions/authActions';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const router = useRouter()
  const dispatch = useDispatch()
  const { data: user, status } = useSession()

  const {error, loading, data: memberResp} = useQuery(GET_YC_MEMBER, {
    variables: {
      email: user?.user?.email
    }
  })
  const userData = memberResp?.yc_members[0]
  console.log('uaeerdata ===============>', userData)
  if(status === "authenticated") {
    const userData = memberResp?.yc_members[0]
    console.log('userData ================>', userData)
    dispatch(addMember(userData));
    user?.user?.noClub === true ? router.replace({pathname: '/yc_regions'}) : router.replace({pathname: '/yachty'})
  }
  const moreThan600px = useMediaQuery('(min-width:600px)');
  const hval = moreThan600px ? "h2" : "h3"
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack padding={2} spacing={2}>
        <div className="flex flex-col items-center justify-center rounded-sm bg-cover bg-[url('../public/blue-water.jpg')] md:sm:bg-[url('../public/starboard-tack.jpg')] h-screen">
          <Typography
            variant={hval}
            className='bottom-32 relative'            
          >
            Yachteee.com
          </Typography>
          <Typography variant='h6' color='primary' className='bottom-32 relative'>
            All things yacht club in your pocket.
          </Typography>          
          <Button
            color='primary'
            variant='contained'
            sx={{margin: 2}}
            onClick={(e) => {
              e.preventDefault()  
              signIn()
            }}
          >
            Enter App
          </Button>
          <Button
            color='primary'
            variant='contained'
            sx={{margin: 2}}
            onClick={signOut}
          >
            Sign Out
          </Button>
        </div>
      </Stack>
    </>
  )
}
